#@copyright : Seifeldin Ahmed Ismail

CC=arm-none-eabi-
CFLAGS= -mcpu=cortex-m3 -gdwarf-2
INCS=-I .
LIBS=
SRC= $(wildcard *.c)
OBJ= $(SRC:.c=.o)
As = $(wildcard *.s)
AsOBJ = $(As:.s=.o)
Project_name=learn_in_depth_Cortex_M3


all: $(Project_name).bin
	@echo "======== Buid is Done ========"

#startup.o: startup.s
#	$(CC)as.exe  $(CFLAGS) $< -o $@  

%.o: %.c 
	$(CC)gcc.exe -c $(CFLAGS) $(INCS) $< -o $@


$(Project_name).elf: $(AsOBJ) $(OBJ)
	$(CC)ld.exe -T linker_script.ld $(LIBS) $(AsOBJ) $(OBJ) -o $@ -Map=Map_file.map

	 
$(Project_name).bin: $(Project_name).elf
	$(CC)objcopy.exe -O binary $< $@
	 
	 	 
clean-all: 
	rm $(OBJ) $(Project_name).elf $(Project_name).bin
	 
clean: 
	rm $(Project_name).elf $(Project_name).bin